language: rust
rust:
  - stable
  - beta
  - nightly

branches:
  only:
  - staging
  - trying
  - master
  - "/^stable\\d+(\\.\\d+)?$/"
  - "/^v\\d++(\\.\\d+)?+(\\.\\d+)?+(\\.\\d+)?$/"

cache: cargo
