[package]
name = "media_import"
version = "0.3.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
chrono = "0.4.6"
docopt = "1.0.2"
failure = "0.1.5"
failure_derive = "0.1.3"
indicatif = "0.11.0"
mime = "0.3.13"
serde = "1.0.87"
serde_derive = "1.0.88"
serde_json = "1.0.38"
tree_magic = "0.2.1"
walkdir = "2.2.7"
xdg = "2.2.0"
