[package]
name = "media_import"
version = "0.3.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
chrono = "0.4.6"
docopt = "1.0.2"
failure = "0.1.3"
failure_derive = "0.1.3"
indicatif = "0.10.3"
mime = "0.3.12"
serde = "1.0.83"
serde_derive = "1.0.83"
serde_json = "1.0.34"
tree_magic = "0.2.1"
walkdir = "2.2.7"
xdg = "2.2.0"
