[package]
name = "media_import"
version = "0.2.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
chrono = "0.4.2"
docopt = "0.8.3"
failure = "0.1.1"
failure_derive = "0.1.1"
mime = "0.3.5"
serde = "1.0.37"
serde_derive = "1.0.37"
serde_json = "1.0.14"
tree_magic = "0.2.0"
walkdir = "2.1.4"
xdg = "2.1.0"
