[package]
name = "media_import"
version = "0.3.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
chrono = "0.4.6"
docopt = "1.0.1"
failure = "0.1.2"
failure_derive = "0.1.1"
indicatif = "0.9.0"
mime = "0.3.12"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
tree_magic = "0.2.0"
walkdir = "2.2.6"
xdg = "2.1.0"
